stages:
- stage: Build
  pool: pgazadob1p
  jobs:
  - job: Build
    steps:
    - template: build.yml
      parameters:
        configurations:
        - dev
        - qa
- stage: Dev
  dependsOn: Build
  pool: PGAZADOR1P
  variables:
  - group: 'PHD DEV'
  jobs:
  - template: deploy.yml
    parameters:
      resources:
      - jobName: 'Dev'
        environment: 'PhdDev'
        webAppName: 'PhdDev'
        resourceGroup: 'PHD-Dev'
        subscription: 'Development'
      buildConfiguration: 'dev'
- stage: Qa
  dependsOn: Build
  pool: PGAZADOR1P
  variables:
  - group: 'PHD QA'
  jobs:
  - template: deploy.yml
    parameters:
      resources:
      - jobName: 'Qa'
        environment: 'PhdQa'
        webAppName: 'PhdQa'
        resourceGroup: 'PHD-Qa'
        subscription: 'QA'
      buildConfiguration: 'qa'