stages:
- stage: Build
  pool: BUILD
  jobs:
  - job: Build
    steps:
    - template: build.yml
      parameters:
        configurations:
        - staging
- stage: Staging
  dependsOn: Build
  pool: PGAZADOR1P
  variables:
  - group: 'PHD STG'
  jobs:
  - template: deploy.yml
    parameters:
      resources:
      - jobName: 'StgEast'
        environment: 'PhdStg'
        webAppName: 'PhdEastStg'
        resourceGroup: 'PHD-STG-EAST'
        subscription: 'Staging'
      - jobName: 'StgWest'
        environment: 'PhdStg'
        webAppName: 'PhdWestStg'
        resourceGroup: 'PHD-STG-WEST'
        subscription: 'Staging'
      buildConfiguration: 'staging'