# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- next

pool:
  vmImage: 'ubuntu-latest'

name: $(BuildDefinitionName)_1.0.$(Rev:r)

steps:
- task: VariableTransformTask@1
  inputs:
    value: '$(Build.BuildNumber)'
    variableName: 'packageVersion'
    IsSecret: false
    transformAction: 'none'
    searchReplace: true
    searchReplaceMethod: 'match'
    searchValue: '[0-9]+\.[0-9]+\.[0-9]+(\-(alpha)|(beta)[0-9])?'
    slice: false
  displayName: 'extract package version'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'UI'
    customRegistry: 'useFeed'
    customFeed: '6d26cbbb-94e5-4db9-ac14-039e14cd6ff9/484bd538-a8f3-4ad5-a52d-e1c1d14f5e1f'
  displayName: 'install dependencies'
- task: AngularCLI@0
  inputs:
    command: 'build'
    project: 'UI'
    arguments: '--project=phd-common'
    prod: false
    DisableAnalytics: false
  displayName: 'build phd-common'
- task: setjsonvalue@1
  inputs:
    filename: 'UI/dist/phd-common/package.json'
    numberOfLevels: '1'
    keyname1: 'version'
    valueToSet: '$(packageVersion)'
  displayName: 'set package version'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'UI/dist/phd-common'
    customCommand: 'publish --ignore-scripts'
    customRegistry: 'useFeed'
    customFeed: '6d26cbbb-94e5-4db9-ac14-039e14cd6ff9/484bd538-a8f3-4ad5-a52d-e1c1d14f5e1f'
  displayName: 'npm publish'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'UI/dist/phd-common'
    ArtifactName: 'drop'
    publishLocation: 'Container'